title: A Yahya Blog
email: support@ayahya.me
description: >
  Welcome one, welcome all. This is the personal blog of Abdullah Yahya.
  All posts and site updates are wholly made by and owned by Abdullah Yahya,
  unless otherwise noted.
baseurl: "/blog"
url: "http://ayahya.me"
home: "../"
twitter_username: abdul_jt
github_username:  MetriclyFrench

# Build Settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
