# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Yahya Blog
email: support@ayahya.me
description: > # this means to ignore newlines until "baseurl:"
  Welcome one, welcome all. This is the personal blog of Abdullah Yahya.
  All posts and site updates are wholly made by and owned by Abdullah Yahya,
  unless otherwise noted. There is no specified reason for this site. I made it in the hopes that
  I would use it as a sort of journal or memory palace. Posts will be about things I am currently undertaking or
  random thoughts. I make this site public in the hopes that it might help others somehow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ayahya.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: abdul_jt
github_username:  MetriclyFrench

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
